version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - demo_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ACTIVE_PROFILE: local
    image: localhost/demo_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: newpassword
    entrypoint:
      - java
      - -jar
      - /app/app.jar
    networks:
      - demo_network

  angular-app:
    build:
      context: ../my-demo-app
      dockerfile: Dockerfile
    image: localhost/demo_angular-app
    ports:
      - "4200:80"
    depends_on:
      - app
    networks:
      - demo_network

volumes:
  postgres_data:

networks:
  demo_network:
    driver: bridge
