apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  template:
    spec:
      containers:
        - name: backend-app
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db.dev.svc.cluster.local:5432/mydatabase"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "devpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  ports:
    - port: 8080
      nodePort: 30009  # different from base if you want
      protocol: TCP
      targetPort: 8080
