apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: localhost/backend-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: NEW_ENV_VAR
              value: "example-value"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://my-postgresql.dev.svc.cluster.local:5432/mydatabase"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"  # Ensure this is the correct password
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31025
