apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base  # This pulls in all resources from your base folder

patchesStrategicMerge:
  - backend-patch.yaml