# kube/overlays/dev/kustomization.yaml

# Pull in all resources from the base
resources:
  - ../../base

# If you want everything in the dev namespace automatically:
namespace: dev

# If you need patches to override e.g. nodePorts or environment variables:
patchesStrategicMerge:
  - backend-deployment-patch.yaml
  - postgres-deployment-patch.yaml
