# Backend Application Configuration
backend:
  service:
    name: backend-app-service
    type: NodePort
    port: 8080
    nodePort: 30009
  replicaCount: 1
  image:
    repository: localhost/backend-app
    tag: latest
    pullPolicy: IfNotPresent
  env:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/mydatabase"
    SPRING_DATASOURCE_USERNAME: "admin"
    SPRING_DATASOURCE_PASSWORD: "password"
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"

# PostgreSQL Configuration
postgresql:
  image:
    repository: postgres
    tag: "13"
  postgresqlPassword: mysecretpassword
  postgresqlUsername: postgres
  postgresqlDatabase: mydatabase
  replicaCount: 1
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  service:
    type: NodePort
    port: 5432
    nodePort: 30001

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myapp.example.com
      paths:
        - path: /api/v1/users
          pathType: Prefix
  tls:
    - hosts:
        - myapp.example.com
      secretName: my-tls-secret
